@extends('layouts.app')

@section('content')
<div class="page-header">
    <div class="page-title">
        <h1>Alerts</h1>
        <p>Manage monitoring alerts generated by the alert engine.</p>
    </div>
    <button class="btn-add" id="openAddAlertBtn">+ Add Alert</button>
</div>

<div class="card-table-container">
    <table class="data-table">
        <thead>
            <tr>
                <th>Device</th>
                <th>Customer</th>
                <th>Severity</th>
                <th>Message</th>
                <th>Status</th>
                <th>Created</th>
                <th class="col-actions">Actions</th>
            </tr>
        </thead>
        <tbody>
            @forelse($alerts as $alert)
            <tr>
                <td style="font-weight:700;">{{ $alert->device->name }}</td>
                <td>{{ $alert->device->user?->name ?? 'Unassigned' }}</td>
                <td><span class="status-badge {{ $alert->severity }}">{{ ucfirst($alert->severity) }}</span></td>
                <td>{{ $alert->message }}</td>
                <td><span class="status-badge {{ $alert->status === 'open' ? 'warning' : 'up' }}">{{ ucfirst($alert->status) }}</span></td>
                <td>{{ $alert->created_at->format('M d, H:i') }}</td>
                <td style="text-align:right;">
                    @if($alert->status === 'open')
                    <form action="{{ route('alerts.close', $alert) }}" method="POST" style="display:inline;">
                        @csrf
                        <button type="submit" class="btn-action edit-btn">Close</button>
                    </form>
                    @endif
                    <button class="btn-action edit-btn editAlertBtn"
                        data-id="{{ $alert->id }}"
                        data-device-id="{{ $alert->device_id }}"
                        data-service-point-id="{{ $alert->service_point_id }}"
                        data-severity="{{ $alert->severity }}"
                        data-message="{{ $alert->message }}"
                        data-status="{{ $alert->status }}">Edit</button>
                    <form action="{{ route('alerts.destroy', $alert) }}" method="POST" style="display:inline;" onsubmit="return confirm('Delete alert?');">
                        @csrf @method('DELETE')
                        <button type="submit" class="btn-action delete-btn">Delete</button>
                    </form>
                </td>
            </tr>
            @empty
            <tr><td colspan="7" style="text-align:center;padding:2rem;color:var(--text-muted);">No alerts found.</td></tr>
            @endforelse
        </tbody>
    </table>
</div>

<div class="modal-overlay" id="alertModal">
    <div class="modal-card modal-card-wide">
        <div class="modal-header">
            <h3 id="alertModalTitle">Add Alert</h3>
            <button class="modal-close" id="closeAlertModal">&times;</button>
        </div>
        <form action="{{ route('alerts.store') }}" method="POST" id="alertForm">
            @csrf
            <div id="alertMethodField"></div>
            <div class="modal-body">
                <div class="form-group">
                    <label>Device</label>
                    <select name="device_id" id="alert_device_id" class="form-control" required>
                        @foreach($devices as $device)
                            <option value="{{ $device->id }}">{{ $device->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>Service Point</label>
                    <select name="service_point_id" id="alert_service_point_id" class="form-control">
                        <option value="">None</option>
                        @foreach($servicePoints as $point)
                            <option value="{{ $point->id }}">{{ $point->service->name }} — {{ $point->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>Severity</label>
                    <select name="severity" id="alert_severity" class="form-control" required>
                        <option value="critical">Critical</option>
                        <option value="warning">Warning</option>
                        <option value="info">Info</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Message</label>
                    <textarea name="message" id="alert_message" class="form-control" rows="3" required></textarea>
                </div>
                <div class="form-group">
                    <label>Status</label>
                    <select name="status" id="alert_status" class="form-control" required>
                        <option value="open">Open</option>
                        <option value="closed">Closed</option>
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn-secondary" id="cancelAlertModal">Cancel</button>
                <button type="submit" class="btn-primary" style="width:auto;padding:0.5rem 1.5rem;">Save</button>
            </div>
        </form>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function () {
    const modal = document.getElementById('alertModal');
    const form = document.getElementById('alertForm');
    const methodField = document.getElementById('alertMethodField');

    function openModal(edit = false, data = {}) {
        document.getElementById('alertModalTitle').textContent = edit ? 'Edit Alert' : 'Add Alert';
        methodField.innerHTML = edit ? '<input type="hidden" name="_method" value="PUT">' : '';
        form.action = edit ? `/alerts/${data.id}` : '{{ route('alerts.store') }}';
        document.getElementById('alert_device_id').value = data.deviceId || '';
        document.getElementById('alert_service_point_id').value = data.servicePointId || '';
        document.getElementById('alert_severity').value = data.severity || 'warning';
        document.getElementById('alert_message').value = data.message || '';
        document.getElementById('alert_status').value = data.status || 'open';
        modal.classList.add('open');
    }

    document.getElementById('openAddAlertBtn').onclick = () => openModal(false);
    document.getElementById('closeAlertModal').onclick = () => modal.classList.remove('open');
    document.getElementById('cancelAlertModal').onclick = () => modal.classList.remove('open');

    document.querySelectorAll('.editAlertBtn').forEach(btn => {
        btn.addEventListener('click', () => openModal(true, {
            id: btn.dataset.id,
            deviceId: btn.dataset.deviceId,
            servicePointId: btn.dataset.servicePointId,
            severity: btn.dataset.severity,
            message: btn.dataset.message,
            status: btn.dataset.status,
        }));
    });
});
</script>
@endsection
